services:
  webapi:
    build: ./WebApi/
    ports:
      - "5001:80"
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"


volumes:
  mongodb-data:
    name: my-mongodb-data
    
